destination: dist
source: jekyll

# Project Info
title: Bolt
description: A minimilist framework for rapid website development.
baseurl:
url: https://jmgoodman27.github.io
permalink: pretty

# Collections
collections:
  blog_tags:
    output: true
    permalink: /blog/:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
highlighter: rouge
theme:
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
